knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        linkedin:
            type: linkedin
            client_id: '%linkedin_client_id%'
            client_secret: '%linkedin_client_secret%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: app_connect_linkedin_check