nelmio_security:
    # prevents framing of the entire site
    clickjacking:
        paths:
            "^/.*": DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    # xss_protection:
    #     enabled: true
    #     mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - "no-referrer"
            - "strict-origin-when-cross-origin"

    # Prevents the browser from sending the cookie along with
    # signed_cookie:
    #     names: ['*']
    csp:
        enabled: true
        report_logger_service: logger
        hosts: []
        content_types: []
        enforce:
            level1_fallback: true
            browser_adaptive:
                enabled: true
            default-src: ["self"]
            script-src:
                - "self"
                - "unsafe-inline"
                - "www.googletagmanager.com"
                - "www.google-analytics.com"
                - "*.google.com"
            style-src:
                - "self"
                - "unsafe-inline"
            img-src:
                - "self"
                - "data:"
                - "mdbootstrap.com"
            font-src:
                - "self"
                - "data:"
            connect-src:
                - "self"
                - "*.google.com"
                - "*.google-analytics.com"
