twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        name_develop: '%app.name_develop%'
        email_develop: '%app.mail_develop%'
        phone_develop: '%app.phone_develop%'
        address_develop: '%app.address_develop%'
        entreprise_name_develop: '%app.entreprise_name_develop%'
        entreprise_site_develop: '%app.entreprise_site_develop%'
        entreprise_siret_develop: '%app.entreprise_siret_develop%'

        gtag: 'G-QHP4BT0R0L'
        gtm: 'GTM-PPXGMV4J'

when@test:
    twig:
        strict_variables: true
