services:
    database:
        # env_file: .env
        image: mysql:latest
        environment:
            MYSQL_DATABASE: "CMS_SF"
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "CMS_SF"
            MYSQL_PASSWORD: "password"
        volumes:
            - database_data:/var/lib/mysql
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - "3306:3306"
    # php:
    #     image: php:8.2-apache
    #     ports:
    #         - '80:80'
    #         - '443:443'
    #     volumes:
    #         - .:/var/www/html
    #     environment:
    #         XDEBUG_MODE: 'debug'
    #         XDEBUG_CONFIG: 'client_host=host.docker.internal'
    #         PHP_IDE_CONFIG: 'serverName=JJA_DEV'
    #         APACHE_DOCUMENT_ROOT: '/var/www/html/public'
    #     depends_on:
    #         - database
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
volumes:
    ###> doctrine/doctrine-bundle ###
    database_data:
    ###< doctrine/doctrine-bundle ###
