<?php

namespace App\Service\Install;

use Symfony\Component\Filesystem\Filesystem;

/**
 * Service to manage environment file creation and configuration
 */
class EnvironmentManager
{
    private Filesystem $filesystem;
    private string $projectDir;

    public function __construct(string $projectDir)
    {
        $this->filesystem = new Filesystem();
        $this->projectDir = $projectDir;
    }

    public function generateEnvironmentFile(array $config): array
    {
        try {
            $envPath = $this->projectDir . '/.env';
            $envLocalPath = $this->projectDir . '/.env.local';
            
            // Generate APP_SECRET if not provided
            if (empty($config['app_secret'])) {
                $config['app_secret'] = $this->generateSecretKey();
            }
            
            $envContent = $this->buildEnvironmentContent($config);
            
            // Write to .env.local to override defaults
            $this->filesystem->dumpFile($envLocalPath, $envContent);
            
            // Ensure proper permissions
            $this->filesystem->chmod($envLocalPath, 0644);
            
            return [
                'success' => true,
                'message' => 'Environment file created successfully',
                'path' => $envLocalPath
            ];
            
        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => 'Environment file creation failed: ' . $e->getMessage()
            ];
        }
    }

    public function validateEnvironmentConfig(array $config): array
    {
        $errors = [];
        
        if (empty($config['app_env'])) {
            $errors[] = 'Application environment is required';
        } elseif (!in_array($config['app_env'], ['prod', 'dev', 'test'])) {
            $errors[] = 'Application environment must be prod, dev, or test';
        }
        
        if (!empty($config['app_secret']) && strlen($config['app_secret']) < 32) {
            $errors[] = 'Application secret must be at least 32 characters long';
        }
        
        if (!empty($config['mailer_dsn'])) {
            if (!$this->validateMailerDsn($config['mailer_dsn'])) {
                $errors[] = 'Invalid mailer DSN format';
            }
        }
        
        return [
            'valid' => empty($errors),
            'errors' => $errors
        ];
    }

    public function backupCurrentEnvironment(): array
    {
        try {
            $envPath = $this->projectDir . '/.env';
            $envLocalPath = $this->projectDir . '/.env.local';
            $backupPath = $this->projectDir . '/.env.backup.' . date('Y-m-d-H-i-s');
            
            $hasBackup = false;
            
            if ($this->filesystem->exists($envLocalPath)) {
                $this->filesystem->copy($envLocalPath, $backupPath . '.local');
                $hasBackup = true;
            }
            
            if ($this->filesystem->exists($envPath)) {
                $this->filesystem->copy($envPath, $backupPath);
                $hasBackup = true;
            }
            
            return [
                'success' => true,
                'message' => $hasBackup ? 'Environment files backed up' : 'No environment files to backup',
                'backup_path' => $hasBackup ? $backupPath : null
            ];
            
        } catch (\Exception $e) {
            return [
                'success' => false,
                'message' => 'Environment backup failed: ' . $e->getMessage()
            ];
        }
    }

    public function generateSecretKey(): string
    {
        return bin2hex(random_bytes(32));
    }

    private function buildEnvironmentContent(array $config): string
    {
        $content = [];
        $content[] = '# Environment file generated by CMS Installation Wizard';
        $content[] = '# Generated on: ' . date('Y-m-d H:i:s');
        $content[] = '';
        
        // Framework configuration
        $content[] = '###> symfony/framework-bundle ###';
        $content[] = 'APP_ENV=' . ($config['app_env'] ?? 'prod');
        $content[] = 'APP_SECRET=' . $config['app_secret'];
        $content[] = '###< symfony/framework-bundle ###';
        $content[] = '';
        
        // Database configuration
        if (!empty($config['database_url'])) {
            $content[] = '###> doctrine/doctrine-bundle ###';
            $content[] = 'DATABASE_URL="' . $config['database_url'] . '"';
            $content[] = '###< doctrine/doctrine-bundle ###';
            $content[] = '';
        }
        
        // Mailer configuration
        if (!empty($config['mailer_dsn'])) {
            $content[] = '###> symfony/mailer ###';
            $content[] = 'MAILER_DSN=' . $config['mailer_dsn'];
            $content[] = '###< symfony/mailer ###';
            $content[] = '';
        }
        
        // CMS specific configuration
        $content[] = '###> cms/configuration ###';
        if (!empty($config['site_name'])) {
            $content[] = 'CMS_SITE_NAME="' . addslashes($config['site_name']) . '"';
        }
        if (!empty($config['site_url'])) {
            $content[] = 'CMS_SITE_URL="' . $config['site_url'] . '"';
        }
        if (!empty($config['admin_email'])) {
            $content[] = 'CMS_ADMIN_EMAIL="' . $config['admin_email'] . '"';
        }
        $content[] = '###< cms/configuration ###';
        $content[] = '';
        
        // Security configuration
        if (!empty($config['cors_allow_origin'])) {
            $content[] = '###> nelmio/cors-bundle ###';
            $content[] = 'CORS_ALLOW_ORIGIN=' . $config['cors_allow_origin'];
            $content[] = '###< nelmio/cors-bundle ###';
            $content[] = '';
        }
        
        return implode("\n", $content);
    }

    private function validateMailerDsn(string $dsn): bool
    {
        // Basic validation for common mailer DSN formats
        $patterns = [
            '/^smtp:\/\/.*/',           // SMTP
            '/^gmail:\/\/.*/',          // Gmail
            '/^sendmail:\/\/.*/',       // Sendmail
            '/^null:\/\/null$/',        // Null transport
            '/^mailgun:\/\/.*/',        // Mailgun
            '/^postmark:\/\/.*/',       // Postmark
        ];
        
        foreach ($patterns as $pattern) {
            if (preg_match($pattern, $dsn)) {
                return true;
            }
        }
        
        return false;
    }

    public function getEnvironmentTemplate(): array
    {
        return [
            'app_env' => 'prod',
            'app_secret' => '',
            'database_url' => '',
            'mailer_dsn' => 'null://null',
            'site_name' => '',
            'site_url' => '',
            'admin_email' => '',
            'cors_allow_origin' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$'
        ];
    }
}