# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.open_register: false
    app.mail_develop: contact@jja-dev.fr
    app.name_develop: ""
    app.phone_develop: ""
    app.address_develop: "1 rue de la paix, 75000 Paris"
    app.entreprise_name_develop: "JJA DEV"
    app.entreprise_site_develop: "https://jja-dev.fr"
    app.entreprise_siret_develop: "12345678901234"
    app.mail_administrateur: "%app.mail_develop%"

    maintenanceMode:
        isMaintenance: false
        ips: ["127.0.0.1", "::1"]

    router.request_context.host: domaine.fr
    router.request_context.scheme: https
    asset.request_context.secure: true

    upload_images_directory: "uploads/images"

    linkedin_client_id: ""
    linkedin_client_secret: ""
    linkedin_redirect_uri: "https://127.0.0.1:8000/linkedin-check"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $uploadImagesDirectory: "%upload_images_directory%"
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventSubscriber\InstallSubscriber:
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    App\EventSubscriber\MaintenanceSubscriber:
        arguments:
            - "%maintenanceMode%"

    App\EventSubscriber\SitemapSubscriber:
        tags:
            - { name: "kernel.event_subscriber", priority: 99 }

    App\Twig\AppExtension:
        tags: ["twig.global"]

    App\Twig\JsonLdService: ~
