name: Symfony
on:
    push:
        branches: [master]
    workflow_run:
        workflows: ["Webpack-build"]
        types:
            - completed
jobs:
    symfony-ovh-deploy:
        runs-on: ubuntu-latest
        steps:
            #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
            # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
            - uses: shivammathur/setup-php@2.30.0
              with:
                  php-version: "8.2"
            - uses: actions/checkout@v4

            - name: OVH
              run: |
                  chmod +x "${GITHUB_WORKSPACE}/.github/scripts/ovh.sh"
                  ${GITHUB_WORKSPACE}/.github/scripts/ovh.sh
              shell: bash
              env:
                  OVH_HOSTING_USER: 
                  OVH_HOSTING_PASSWORD: 
                  OVH_HOSTING_DOMAIN: 
                  REPOSITORY_NAME: 
                  REPOSITORY_URL: 
